"""
Isaac Refinement — Post-process grasp_graph.pkl in Isaac Sim
=============================================================
Loads a grasp graph generated by run_grasp_generation.py and refines
each grasp in Isaac Sim to correct FK discrepancies between
pytorch_kinematics and Isaac Sim.

Usage:
    /workspace/IsaacLab/isaaclab.sh -p scripts/refine_grasps.py \
        --grasp_graph data/grasp_graph.pkl --headless
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from isaaclab.app import AppLauncher


def parse_args():
    p = argparse.ArgumentParser(description="Refine grasps in Isaac Sim")
    p.add_argument("--grasp_graph", type=str, required=True,
                   help="Path to grasp_graph.pkl from run_grasp_generation.py")
    p.add_argument("--batch_envs", type=int, default=16,
                   help="Batch size for Isaac refinement environments")
    p.add_argument("--keep_top_k", type=int, default=None,
                   help="Keep only top-K lowest-error grasps per object")
    AppLauncher.add_app_launcher_args(p)
    return p.parse_args()


def main():
    args = parse_args()
    app_launcher = AppLauncher(args)
    sim_app = app_launcher.app

    try:
        from grasp_generation import refine_multi_object_graph_with_isaac
        from grasp_generation.rrt_expansion import MultiObjectGraspGraph

        graph_path = Path(args.grasp_graph)
        if not graph_path.exists():
            print(f"ERROR: {graph_path} not found")
            sys.exit(1)

        print(f"\n{'='*55}")
        print(f" Isaac Refinement")
        print(f" Input: {graph_path}")
        print(f"{'='*55}")

        graph = MultiObjectGraspGraph.load(str(graph_path))
        graph.summary()

        print(f"\nRefining with batch_envs={args.batch_envs}...")
        graph = refine_multi_object_graph_with_isaac(
            graph,
            batch_envs=args.batch_envs,
            keep_top_k=args.keep_top_k,
        )

        # Save refined graph (overwrite)
        graph.save(str(graph_path))

        print(f"\n{'='*55}")
        print(f" Refinement Complete")
        print(f"{'='*55}")
        graph.summary()

        # Print refinement stats
        for name, g in graph.graphs.items():
            errs = [
                float(gr.reset_contact_error)
                for gr in g.grasp_set.grasps
                if getattr(gr, "reset_contact_error", None) is not None
            ]
            if errs:
                import numpy as np
                print(f"  {name}: reset_err mean={np.mean(errs):.4f}m, "
                      f"best={np.min(errs):.4f}m, worst={np.max(errs):.4f}m")

        print(f"\n  Saved: {graph_path}")
        print(f"\nNext step:")
        print(f"  /workspace/IsaacLab/isaaclab.sh -p scripts/train_rl.py "
              f"--grasp_graph {graph_path} --num_envs 512 --headless")

    finally:
        sim_app.close()


if __name__ == "__main__":
    main()
